// Static seed data for the usmdss backend.
// Scholarships mirror the original frontend mock; the demo user, applications,
// documents and notifications populate a realistic first-run experience.

export const scholarships = [
  {
    id: 'sch-getfund',
    name: 'GETFund National Scholarship',
    provider: 'Ghana Education Trust Fund',
    providerType: 'Government',
    logoColor: 'bg-emerald-600',
    initials: 'GF',
    amount: 'Full tuition + GH₵ 6,000 stipend',
    amountValue: 14000,
    deadline: '2026-07-31',
    region: ['All'],
    programmes: ['All'],
    maxAggregate: 12,
    needBased: true,
    slots: 1200,
    applicants: 8420,
    summary:
      'Government-funded award covering full tuition and an annual upkeep stipend for academically qualified, financially needy Ghanaian students in accredited tertiary institutions.',
    benefits: ['Full tuition for the programme duration', 'GH₵ 6,000 annual stipend', 'Book and research allowance', 'Renewable each academic year'],
    documents: ['Ghana Card', 'WASSCE Results Slip', 'Admission Letter', 'Financial Need Statement'],
    tags: ['Need-based', 'Renewable', 'Nationwide'],
  },
  {
    id: 'sch-mtn',
    name: 'MTN Bright Scholarship',
    provider: 'MTN Ghana Foundation',
    providerType: 'Corporate',
    logoColor: 'bg-amber-500',
    initials: 'MB',
    amount: 'GH₵ 10,000 / year',
    amountValue: 10000,
    deadline: '2026-07-14',
    region: ['All'],
    programmes: ['BSc Computer Engineering', 'BSc Computer Science', 'BSc Electrical Engineering', 'BSc Mathematics', 'BSc Physics'],
    maxAggregate: 10,
    needBased: true,
    slots: 150,
    applicants: 3110,
    summary:
      'Awarded to high-performing students from underserved backgrounds pursuing STEM programmes, with priority on ICT and engineering disciplines.',
    benefits: ['GH₵ 10,000 annual award', 'Paid internship at MTN Ghana', 'Mentorship and career coaching', 'Laptop and data bundle'],
    documents: ['Ghana Card', 'WASSCE Results Slip', 'Admission Letter', 'Recommendation Letter'],
    tags: ['STEM', 'Mentorship', 'Internship'],
  },
  {
    id: 'sch-mastercard',
    name: 'Mastercard Foundation Scholars',
    provider: 'Mastercard Foundation',
    providerType: 'Foundation',
    logoColor: 'bg-orange-600',
    initials: 'MC',
    amount: 'Comprehensive (full cost)',
    amountValue: 22000,
    deadline: '2026-08-20',
    region: ['All'],
    programmes: ['All'],
    maxAggregate: 14,
    needBased: true,
    slots: 200,
    applicants: 5240,
    summary:
      'A comprehensive scholarship covering tuition, accommodation, meals, books and a monthly stipend, with leadership development for young Africans committed to giving back.',
    benefits: ['Full cost of attendance', 'Accommodation and meals', 'Monthly personal stipend', 'Leadership and entrepreneurship training'],
    documents: ['Ghana Card', 'WASSCE Results Slip', 'Admission Letter', 'Financial Need Statement', 'Personal Essay'],
    tags: ['Comprehensive', 'Leadership', 'Need-based'],
  },
  {
    id: 'sch-district',
    name: 'District-Level Scholarship Scheme',
    provider: 'Ghana Scholarships Secretariat',
    providerType: 'Government',
    logoColor: 'bg-teal-700',
    initials: 'DS',
    amount: 'GH₵ 4,500 / year',
    amountValue: 4500,
    deadline: '2026-07-05',
    region: ['Ashanti', 'Bono', 'Ahafo', 'Bono East'],
    programmes: ['All'],
    maxAggregate: 15,
    needBased: true,
    slots: 800,
    applicants: 6190,
    summary:
      'Decentralised award administered through the Metropolitan, Municipal and District Assemblies (MMDAs) for indigenes of the district pursuing accredited tertiary programmes.',
    benefits: ['GH₵ 4,500 annual award', 'District-level mentorship', 'Priority for renewal', 'Community service placement'],
    documents: ['Ghana Card', 'WASSCE Results Slip', 'Admission Letter', 'Proof of District of Origin'],
    tags: ['District', 'Interview required', 'Renewable'],
  },
  {
    id: 'sch-stanbic',
    name: 'Stanbic Bank Future Leaders',
    provider: 'Stanbic Bank Ghana',
    providerType: 'Corporate',
    logoColor: 'bg-blue-700',
    initials: 'SB',
    amount: 'GH₵ 8,000 / year',
    amountValue: 8000,
    deadline: '2026-09-10',
    region: ['All'],
    programmes: ['BA Economics', 'BSc Business Administration', 'BSc Mathematics', 'BSc Computer Science', 'BSc Computer Engineering'],
    maxAggregate: 11,
    needBased: false,
    slots: 60,
    applicants: 1880,
    summary:
      'Merit award for outstanding students in business, finance and analytics disciplines, with a fast-track route into the bank graduate programme.',
    benefits: ['GH₵ 8,000 annual award', 'Graduate scheme fast-track', 'Financial literacy bootcamp', 'Networking with industry leaders'],
    documents: ['Ghana Card', 'WASSCE Results Slip', 'Admission Letter', 'Statement of Purpose'],
    tags: ['Merit', 'Business', 'Career track'],
  },
  {
    id: 'sch-chevening',
    name: 'Chevening-Ghana Undergraduate Link',
    provider: 'UK Government (FCDO)',
    providerType: 'International',
    logoColor: 'bg-indigo-700',
    initials: 'CV',
    amount: 'GH₵ 18,000 + exchange term',
    amountValue: 18000,
    deadline: '2026-10-01',
    region: ['All'],
    programmes: ['All'],
    maxAggregate: 8,
    needBased: false,
    slots: 25,
    applicants: 2400,
    summary:
      'Highly selective international award offering funding plus a one-term exchange at a partner UK university for exceptional students with leadership potential.',
    benefits: ['GH₵ 18,000 annual award', 'One-term UK exchange', 'Global alumni network', 'Leadership residential'],
    documents: ['Ghana Card', 'WASSCE Results Slip', 'Admission Letter', 'Two Recommendation Letters', 'Leadership Essay'],
    tags: ['International', 'Highly selective', 'Exchange'],
  },
]

// Demo user — password is "demopassword" (hashed at seed time).
export const demoUser = {
  id: 'usr-benjamin',
  name: 'Benjamin Darko',
  firstName: 'Benjamin',
  email: 'benjamin.darko@st.knust.edu.gh',
  password: 'demopassword',
  phone: '+233 24 712 0098',
  studentId: '1821122',
  programme: 'BSc Computer Engineering',
  institution: 'Kwame Nkrumah University of Science & Technology',
  level: '100 · First Year',
  region: 'Ashanti',
  homeDistrict: 'Kumasi Metropolitan',
  wassceAggregate: 8,
  gender: 'Male',
  needLevel: 'High',
  avatarColor: 'from-brand-500 to-brand-700',
}

// Applications seeded for the demo user (reference scholarship ids above).
export const demoApplications = [
  {
    id: 'app-1',
    userId: demoUser.id,
    scholarshipId: 'sch-mtn',
    status: 'Interview',
    submittedOn: '2026-06-12',
    lastUpdate: '2026-06-26',
    progress: 75,
    timeline: [
      { label: 'Application submitted', date: '12 Jun 2026', done: true },
      { label: 'Documents verified', date: '18 Jun 2026', done: true },
      { label: 'Shortlisted for interview', date: '26 Jun 2026', done: true },
      { label: 'Interview scheduled', date: '03 Jul 2026', done: false },
      { label: 'Final decision', date: 'Expected 15 Jul', done: false },
    ],
  },
  {
    id: 'app-2',
    userId: demoUser.id,
    scholarshipId: 'sch-getfund',
    status: 'Under Review',
    submittedOn: '2026-06-20',
    lastUpdate: '2026-06-24',
    progress: 50,
    timeline: [
      { label: 'Application submitted', date: '20 Jun 2026', done: true },
      { label: 'Documents verified', date: '24 Jun 2026', done: true },
      { label: 'Eligibility review', date: 'In progress', done: false },
      { label: 'Award decision', date: 'Expected 31 Jul', done: false },
    ],
  },
  {
    id: 'app-3',
    userId: demoUser.id,
    scholarshipId: 'sch-district',
    status: 'Submitted',
    submittedOn: '2026-06-28',
    lastUpdate: '2026-06-28',
    progress: 25,
    timeline: [
      { label: 'Application submitted', date: '28 Jun 2026', done: true },
      { label: 'Documents verification', date: 'Pending', done: false },
      { label: 'District interview', date: 'To be scheduled', done: false },
      { label: 'Award decision', date: 'Expected 20 Jul', done: false },
    ],
  },
  {
    id: 'app-4',
    userId: demoUser.id,
    scholarshipId: 'sch-mastercard',
    status: 'Draft',
    submittedOn: '—',
    lastUpdate: '2026-06-27',
    progress: 10,
    timeline: [
      { label: 'Draft started', date: '27 Jun 2026', done: true },
      { label: 'Personal essay', date: 'Incomplete', done: false },
      { label: 'Submit application', date: 'Due 20 Aug', done: false },
    ],
  },
]

export const demoDocuments = [
  { id: 'doc-1', userId: demoUser.id, name: 'Ghana Card (Front & Back)', type: 'PDF', category: 'Identity', size: '1.2 MB', uploadedOn: '02 Jun 2026', status: 'Verified', linkedApplications: 4, encrypted: true },
  { id: 'doc-2', userId: demoUser.id, name: 'WASSCE Results Slip', type: 'PDF', category: 'Academic', size: '840 KB', uploadedOn: '02 Jun 2026', status: 'Verified', linkedApplications: 4, encrypted: true },
  { id: 'doc-3', userId: demoUser.id, name: 'KNUST Admission Letter', type: 'PDF', category: 'Admission', size: '510 KB', uploadedOn: '05 Jun 2026', status: 'Verified', linkedApplications: 3, encrypted: true },
  { id: 'doc-4', userId: demoUser.id, name: 'Financial Need Statement', type: 'PDF', category: 'Financial', size: '320 KB', uploadedOn: '11 Jun 2026', status: 'Pending', linkedApplications: 2, encrypted: true },
  { id: 'doc-5', userId: demoUser.id, name: 'Recommendation Letter — Mr. Owusu', type: 'PDF', category: 'Other', size: '290 KB', uploadedOn: '14 Jun 2026', status: 'Verified', linkedApplications: 1, encrypted: true },
  { id: 'doc-6', userId: demoUser.id, name: 'Proof of District of Origin', type: 'JPG', category: 'Identity', size: '1.8 MB', uploadedOn: '—', status: 'Action needed', linkedApplications: 0, encrypted: true },
]

export const demoNotifications = [
  { id: 'n-1', userId: demoUser.id, channel: 'SMS', category: 'Interview', title: 'Interview scheduled', body: 'MTN Bright Scholarship interview set for Thu 03 Jul, 10:00 AM at MTN House, Accra. Reply 1 to confirm.', time: '2 hours ago', read: false },
  { id: 'n-2', userId: demoUser.id, channel: 'SMS', category: 'Deadline', title: 'Deadline in 6 days', body: 'District-Level Scholarship closes 05 Jul 2026. Your application is submitted; upload Proof of Origin to complete.', time: '5 hours ago', read: false },
  { id: 'n-3', userId: demoUser.id, channel: 'Email', category: 'Status', title: 'Documents verified', body: 'Your GETFund National Scholarship documents have passed verification. Eligibility review is now in progress.', time: 'Yesterday', read: false },
  { id: 'n-4', userId: demoUser.id, channel: 'System', category: 'Match', title: '3 new strong matches', body: 'We found 3 new scholarships matching your profile after the June criteria update.', time: 'Yesterday', read: true },
  { id: 'n-5', userId: demoUser.id, channel: 'Email', category: 'Deadline', title: 'MTN deadline reminder', body: 'MTN Bright Scholarship closes 14 Jul 2026. You have an active application in progress.', time: '2 days ago', read: true },
  { id: 'n-6', userId: demoUser.id, channel: 'System', category: 'System', title: 'Profile 92% complete', body: 'Add a leadership essay to unlock eligibility for the Chevening-Ghana Undergraduate Link.', time: '3 days ago', read: true },
]
