# Generated by Django 6.0.7 on 2026-07-16 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('Government', 'Government'), ('Corporate', 'Corporate'), ('International', 'International'), ('Foundation', 'Foundation')], max_length=20)),
                ('logo_color', models.CharField(default='bg-emerald-600', max_length=30)),
                ('initials', models.CharField(max_length=4)),
                ('amount', models.CharField(max_length=100)),
                ('amount_value', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('region', models.JSONField(default=list, help_text='List of eligible regions or ["All"]')),
                ('programmes', models.JSONField(default=list, help_text='List of eligible programmes or ["All"]')),
                ('max_aggregate', models.IntegerField(default=36)),
                ('need_based', models.BooleanField(default=False)),
                ('slots', models.IntegerField(default=0)),
                ('applicants', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('benefits', models.JSONField(default=list)),
                ('documents', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('System', 'System')], max_length=10)),
                ('category', models.CharField(choices=[('Deadline', 'Deadline'), ('Status', 'Status'), ('Interview', 'Interview'), ('Match', 'Match'), ('System', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time', models.CharField(max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Awarded', 'Awarded'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('submitted_on', models.CharField(default='—', max_length=20)),
                ('last_update', models.DateField(auto_now=True)),
                ('progress', models.IntegerField(default=0)),
                ('timeline', models.JSONField(default=list, help_text='List of {label, date, done} objects')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=30)),
                ('programme', models.CharField(blank=True, max_length=120)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('home_district', models.CharField(blank=True, max_length=100)),
                ('wassce_aggregate', models.IntegerField(default=36)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('need_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=20)),
                ('avatar_color', models.CharField(default='from-brand-500 to-brand-700', max_length=60)),
                ('profile_completion', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(default='PDF', max_length=10)),
                ('category', models.CharField(choices=[('Identity', 'Identity'), ('Academic', 'Academic'), ('Admission', 'Admission'), ('Financial', 'Financial'), ('Other', 'Other')], max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('uploaded_on', models.CharField(default='—', max_length=20)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Action needed', 'Action needed')], default='Pending', max_length=20)),
                ('linked_applications', models.IntegerField(default=0)),
                ('encrypted', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Strong match', 'Strong match'), ('Partial match', 'Partial match'), ('Not eligible', 'Not eligible')], max_length=20)),
                ('criteria', models.JSONField(default=list, help_text='List of {label, met, detail} objects')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.scholarship')),
            ],
            options={
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
