# Generated by Django 6.0.7 on 2026-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vault_documents/'),
        ),
    ]
