# Generated by Django 5.2.16 on 2026-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vaultdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='origin',
            field=models.CharField(choices=[('scraped', 'Scraped from live site'), ('seeded', 'Seeded demo data'), ('curated', 'Curated fallback — not confirmed against the live site')], default='scraped', help_text="Where this row came from. 'curated' means the live scrape failed and hardcoded data was substituted, so its figures are unverified.", max_length=10),
        ),
    ]
