# Generated by Django 5.2.16 on 2026-07-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scholarship_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='level_scope',
            field=models.CharField(choices=[('shs', 'SHS students (funding to complete SHS)'), ('tertiary_entry', 'Entering tertiary (SHS graduates / level 100)'), ('tertiary_continuing', 'Continuing tertiary students'), ('tertiary_any', 'Any undergraduate'), ('postgraduate', 'Postgraduate'), ('unknown', 'Not classified')], default='unknown', help_text="Which students this award is for. 'unknown' caps matches at Partial because eligibility cannot be confirmed.", max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_standing',
            field=models.CharField(blank=True, choices=[('First Class', 'First Class'), ('Second Class Upper', 'Second Class Upper'), ('Second Class Lower', 'Second Class Lower'), ('Third Class', 'Third Class'), ('Pass', 'Pass'), ('No results yet', 'No results yet')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs_level',
            field=models.CharField(blank=True, choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Completed', 'Completed SHS')], max_length=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='shs_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(blank=True, choices=[('SHS', 'SHS student'), ('University', 'University student')], max_length=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university_level',
            field=models.CharField(blank=True, choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('Postgraduate', 'Postgraduate')], max_length=14),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wassce_status',
            field=models.CharField(blank=True, choices=[('not_written', 'Not yet written'), ('awaiting', 'Awaiting results'), ('released', 'Results released')], max_length=12),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='wassce_aggregate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
