# Generated by Django 5.2.16 on 2026-07-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scholarship_level_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='The live page this scholarship was scraped from, so students can verify and apply at the original listing.', max_length=500),
        ),
    ]
