# Generated by Django 6.0.7 on 2026-07-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_curated_scholarships'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attached_documents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vaultdocument',
            name='doc_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
