# Generated by Django 6.0.7 on 2026-08-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_application_attached_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='application_email',
            field=models.EmailField(blank=True, default='', help_text='Where to send the application when the mode is email.', max_length=254),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_mode',
            field=models.CharField(choices=[('online', "Apply online on the provider's portal"), ('email', 'Apply by email'), ('offline', 'Apply in person / by post'), ('unknown', 'Not stated')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_url',
            field=models.URLField(blank=True, default='', help_text='Direct link to the provider application form or portal.', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='gender_scope',
            field=models.CharField(choices=[('any', 'Open to all genders'), ('female', 'Women only'), ('male', 'Men only')], default='any', help_text="Restrict this award to one gender. Women-only funds use 'female'.", max_length=10),
        ),
    ]
