# Generated by Django 6.0.7 on 2026-08-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_women_only_scholarships'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='application_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
