# Generated by Django 6.0.7 on 2026-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_drop_em_dash_placeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='origin',
            field=models.CharField(choices=[('scraped', 'Scraped from live site'), ('seeded', 'Seeded demo data'), ('curated', 'Curated fallback, not confirmed against the live site')], default='scraped', help_text="Where this row came from. 'curated' means the live scrape failed and hardcoded data was substituted, so its figures are unverified.", max_length=10),
        ),
    ]
