# Generated by Django 6.0.7 on 2026-08-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_scholarship_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='application_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Ranked application candidates: [{url, score, reason, kind, host, embeddable}].'),
        ),
    ]
