# Generated by Django 5.2.16 on 2026-08-10 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_scholarship_application_candidates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sms_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], max_length=10)),
                ('recipient', models.CharField(blank=True, help_text='E.164 number or email address. Blank when the profile held nothing usable.', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], max_length=10)),
                ('provider', models.CharField(default='console', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, help_text='The in-app alert this delivery accompanied, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='core.notification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('channel', 'dedupe_key'), name='unique_outbound_channel_dedupe_key')],
            },
        ),
    ]
