# Generated by Django 6.0.7 on 2026-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsource',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='Number of consecutive scraping failures'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='cooldown_hours',
            field=models.IntegerField(default=6, help_text='Minimum hours between scrapes of this source'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='max_delay',
            field=models.FloatField(default=10.0, help_text='Maximum delay in seconds between requests to this source'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='max_failures_before_cooldown',
            field=models.IntegerField(default=3, help_text='Number of failures before triggering a cooldown'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='min_delay',
            field=models.FloatField(default=5.0, help_text='Minimum delay in seconds between requests to this source'),
        ),
        migrations.AddField(
            model_name='scrapingsource',
            name='scrape_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors and parsing config per source'),
        ),
    ]
