# Generated by Django 6.0.7 on 2026-07-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapingsource_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingsource',
            name='scraper_type',
            field=models.CharField(choices=[('api', 'API / RSS (WordPress REST or feed)'), ('generic', 'Generic (HTML)'), ('selenium', 'Selenium'), ('playwright', 'Playwright')], max_length=50),
        ),
    ]
